version: '3'
services:
  postgres:
    image: 'postgres'
    restart: on-failure
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'pg123456'
    ports:
      - "5432:5432"
    container_name: pg_1
